name: check-build

# Using Event to trigger workflows

# THe following will run when any push is made to any branch
on:
  # scheduling workflows
  # see: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
  schedule:
    - cron: '0 22 * * *'

jobs:
  cargo-check:
    # see: https://docs.github.com/en/actions/using-jobs/using-conditions-to-control-job-execution
    if: github.repository == 'main'
    name: cargo-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: echo "running cargo checks at 22:00"
      - run: cargo check
      - run: cargo check --examples
      - run: cargo check --tests